// creating function getComputerChoice to generate random responses as computer
function getComputerChoice() {
  // created array to store responses
  const computerChoice = ["Rock", "Paper", "Scissors"];
  // created random number for generating index between 0 to 2 to get data from array
  let random = Math.floor(Math.random() * 3);
  // created variable for getting responses from stored response array by indices generated by random number
  let randomComputerChoice = computerChoice[random];
  // returning variable so that it is available to use further
  return randomComputerChoice;
}
// created variables for storing data and result
let playerScore = 0;
let computerScore = 0;

// created playRound function to generate 1 round for the game
function playRound(e) {
  const computerSelection = getComputerChoice();
  const playerSelection = e.target.textContent;
  // Check for a tie
  if (playerSelection === computerSelection) {
    displayResult("It's a tie!");
  }
  // Check for computer win
  else if ((playerSelection === "Rock" && computerSelection === "Paper") || (playerSelection === "Paper" && computerSelection === "Scissors") || (playerSelection === "Scissors" && computerSelection === "Rock")) {
      updateScore("computer");
      displayResult(`You lose! ${computerSelection} beats ${playerSelection}.`);
  }
  // Check for player win
  else if ((computerSelection === "Rock" && playerSelection === "Paper") || (computerSelection === "Paper" && playerSelection === "Scissors") || (computerSelection === "Scissors" && playerSelection === "Rock")) {
    updateScore("player");
    displayResult(`You win! ${playerSelection} beats ${computerSelection}.`);
  }
  else {
    displayResult("Invalid selection. Please choose rock, paper, or scissors.");
  }
  // Check for game winner
  if (playerScore === 5) {
    announceWinner("You");
    resetGame();
  } else if (computerScore === 5) {
    announceWinner("Computer");
    resetGame();
  }
}

function displayResult(message) {
  const resultsDiv = document.getElementById("results");
  resultsDiv.textContent = message;
}

function updateScore(winner) {
  if (winner === "player") {
    playerScore++;
  } else if (winner === "computer") {
    computerScore++;
  }

  const scoreboardDiv = document.getElementById("scoreboard");
  scoreboardDiv.textContent = `Player: ${playerScore} | Computer: ${computerScore}`;
}

function announceWinner(winner) {
  const resultsDiv = document.getElementById("results");
  resultsDiv.textContent = `${winner} wins the game!`;

  const buttons = document.querySelectorAll("button");
  buttons.forEach((button) => (button.disabled = true));
}

function resetGame() {
  playerScore = 0;
  computerScore = 0;

  const scoreboardDiv = document.getElementById("scoreboard");
  scoreboardDiv.textContent = "Player: 0 | Computer: 0";

  const buttons = document.querySelectorAll("button");
  buttons.forEach((button) => (button.disabled = false));
}

// Add event listeners to the buttons
const rockButton = document.getElementById("rock");
rockButton.addEventListener("click", playRound);

const paperButton = document.getElementById("paper");
paperButton.addEventListener("click", playRound);

const scissorsButton = document.getElementById("scissors");
scissorsButton.addEventListener("click", playRound);