// creating function getComputerChoice to generate random responses as computer
function getComputerChoice() {
  // created array to store responses
  const computerChoice = ["Rock", "Paper", "Scissors"];
  // created random number for generating index between 0 to 2 to get data from array
  let random = Math.floor(Math.random() * 3);
  // created variable for getting responses from stored response array by indices generated by random number
  let randomComputerChoice = computerChoice[random];
  // returning variable so that it is available to use further
  return randomComputerChoice;
}
// created variables for storing data and result
let answer = "";
let playerGameWon = 0;
let computerGameWon = 0;
let response = {};

// created playRound function to generate 1 round for the game
function playRound(playerSelection, computerSelection) {
  // storing response of user and make is capital case to avoid case sensitive issues
  let playerChoice =
    playerSelection[0].toUpperCase() + playerSelection.slice(1);
  // checking both the responses
  console.log(playerChoice);
  console.log(computerSelection);
  // comparing both responses to declare the winner, loser and tie
  if (playerChoice == computerSelection) {
    answer = "Match Draw";
  } else if (
    (playerChoice == "Rock" && computerSelection == "Scissors") ||
    (playerChoice == "Scissors" && computerSelection == "Paper") ||
    (playerChoice == "Paper" && computerSelection == "Rock")
  ) {
    answer = `You Win! ${playerChoice} beats ${computerSelection}`;
    // increaing counter for player win so that we can declare final result based on score
    playerGameWon++;
  } else if (
    (playerChoice == "Rock" && computerSelection == "Paper") ||
    (playerChoice == "Scissors" && computerSelection == "Rock") ||
    (playerChoice == "Paper" && computerSelection == "Scissors")
  ) {
    answer = `You Lose! ${computerSelection} beats ${playerChoice}`;
    // increaing counter for computer win so that we can declare final result based on score
    computerGameWon++;
  }
  // returning am object to use these values later in main game function
  return (response = {
    answer: answer,
    computerGameWon: computerGameWon,
    playerGameWon: playerGameWon,
  });
}

let playerSelection;
let computerSelection = getComputerChoice();

// this was the work done by me in which I hard coded the function and it was no flexible to catter more games
// function game (playerSelection, computerSelection) {
//     let message = "";
//     playRound(playerSelection, computerSelection)
//     console.log(response.answer);
//     let player2 = prompt("Enter Rock, Paper or Scissors").toLowerCase();
//     let computer2 = getComputerChoice();
//     playRound(player2, computer2);
//     console.log(response.answer);
//     let player3 = prompt("Enter Rock, Paper or Scissors").toLowerCase();
//     let computer3 = getComputerChoice();
//     playRound(player3, computer3);
//     console.log(response.answer);
//     let player4 = prompt("Enter Rock, Paper or Scissors").toLowerCase();
//     let computer4 = getComputerChoice();
//     playRound(player4, computer4);
//     console.log(response.answer);
//     let player5 = prompt("Enter Rock, Paper or Scissors").toLowerCase();
//     let computer5 = getComputerChoice();
//     playRound(player5, computer5);
//     console.log(response.answer);
//     if (response.computerGameWon == response.playerGameWon) {
//         message = "Match Draw!";
//     } else if (response.computerGameWon > response.playerGameWon) {
//         message = "You Lose!";
//     } else if (response.computerGameWon < response.playerGameWon) {
//         message = "You Win!";
//     }
//     return message;
// }
// console.log(game(playerSelection, computerSelection));

// this is the main function which calls playRound function to generate game
function game(playerSelection, computerSelection) {
    // this message vairable will display final result
  let message = "";
  let i = 1;
  // created loop till i <= 5 so that the game can have 5 rounds and based on that result will be anounced
  while (i <= 5) {
    // getting user input and make it all lower to avoid case sensitive issues
    playerSelection = prompt("Enter Rock, Paper or Scissors").toLowerCase();
    // calling playRound for the game and comparision of both the responses
    playRound(playerSelection, computerSelection);
    console.log(response.answer);
    // getting computer response for every round of game
    computerSelection = getComputerChoice();
    i++;
  }
  // comparing the final results and based on that result will be announced
  if (response.computerGameWon == response.playerGameWon) {
    message = "Match Draw!";
  } else if (response.computerGameWon > response.playerGameWon) {
    message = "You Lose!";
  } else if (response.computerGameWon < response.playerGameWon) {
    message = "You Win!";
  }
  return message;
}
console.log(game(playerSelection, computerSelection));